version: '3.1'
services:
  mongodb:
    image: mongo
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_DB_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_DB_PWD}
  mongo-express:
    image: mongo-express
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=${MONGO_DB_USERNAME}
      - ME_CONFIG_MONGODB_ADMINPASSWORD=${MONGO_DB_PWD}
      - ME_CONFIG_MONGODB_SERVER=mongodb
    depends_on:
    - "mongodb"